CELL_SIZE = 0.4  # meter
NODE_RESOLUTION = 2.0 # meter

FREE = 0
OCCUPIED = 100
UNKNOWN = -1

SENSOR_RANGE = 20  # meter
UTILITY_RANGE = 0.5 * SENSOR_RANGE
MIN_UTILITY = 3
FRONTIER_CELL_SIZE = 1 * CELL_SIZE

UPDATING_MAP_SIZE = 4 * SENSOR_RANGE + 4 * NODE_RESOLUTION

NODE_INPUT_DIM = 4
EMBEDDING_DIM = 128
K_SIZE = 25

THR_TO_WAYPOINT = 1 # meter
THR_NEXT_WAYPOINT = 5 # meter
THR_GRAPH_HARD_UPDATE = 8 # meter

CLUSTER_RANGE = 10 # meter

AVOID_OSCILLATION = True